### ISSUE TITLE
Send full image url for 'image' type content blocks from API

### ISSUE THREAD

**Issue by foglabs** [WGBH-MLA/ov-wag#114]
### Because

when an image block is received from the API, the 'value' field contains the image id, rather than the image url:

![Screen Shot 2023-11-15 at 3 50 35 PM](https://github.com/WGBH-MLA/ov-wag/assets/8140840/40d52166-b489-47e6-81fe-18cdca344360)

since we intend to use s3 URLs in production on the frontend, we should get the image's full URL from the API. this will probably just involve modifying the serializer(s) for content blocks.

### Done when

API returns the full image URL when sending image blocks to consumers.

**Comment by mrharpo** [comment]
Completed with #101 

Urls are now returned as signed links to the production S3 bucket.
