### ISSUE TITLE
Make Hero Image and Cover Image required for Exhibit and Collection

### ISSUE THREAD

**Issue by foglabs** [WGBH-MLA/ov-wag#154]
### Because

Because hero image _and_ cover image are used across the site on various pages, exhibits and collections should require both image fields to be filled.

### Done when

- [ ]

**Comment by mrharpo** [comment]
@foglabs I like the idea, but I'm not sure if it should be a hard requirement for the record. E.g:

if a content editor wants to create a record stub (as a draft) they would have to add both images (or 2 placeholders) before they could save it, even as a draft. 

# Hooks
Wagtail has a [before-publish-page hook](https://docs.wagtail.org/en/stable/reference/hooks.html#before-publish-page) that we can use to make sure everything is there before publishing.

With that in mind, can the frontend render a placeholder image (OV logo?) to display on demo for such cases?
