### ISSUE TITLE
API Needs To Transform wagtails' image <embed> elements in Page body into usable images

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/ov-wag#16]
Because:
The wagtail page editor allows users to upload and insert images into the page body, but when the page body is sent from the API, images appear as the following: 
`<embed alt="flutin" embedtype="image" format="left" id="2"/>`

We need to be able to show the image via an `<img />` element in the page body, so we need a transformation from the `<embed />` tag to an `<img />` with the appropriate Image model's url and alt text. Ideally, this transform could be done in the wagtail API router, rather than through a second http request from the frontend.

Done When:
Page body can be received through API, with images transformed from `<embed />` tags to `<img />` elements

**Comment by mrharpo** [comment]
A nice solution is here: https://stackoverflow.com/a/50467053
``` python3
from wagtail.core.templatetags import wagtailcore_tags

def MyPage(Page):
    body = RichTextField()

    def rendered_body(self):
        return wagtailcore_tags.richtext(self.body)

    api_fields = [
        APIField('rendered_body'),
    ]
```

This correctly returns `<img>` tags in place of the `<embed>`.

The only issue is the API field will be named `rendered_body` (or whatever we call it). It would be nice if we can do this with a custom `serializer`, but I have yet to get it working correctly.

**Comment by mrharpo** [comment]
Got it working with a serializer!
``` python3
class RichTextSerializer(Field):
    def to_representation(self, value):
        return wagtailcore_tags.richtext(value)
```

**Comment by foglabs** [comment]
awesome!
