### ISSUE TITLE
set order of collections and exhibits on display pages

### ISSUE THREAD

**Issue by phigg** [WGBH-MLA/ov-wag#173]
Is it possible to set the order of the how collections and exhibits appear on their respective display pages? Currently, they appear in the order they are published in Wagtail. Unpublishing and re-publishing exhibits doesn't permanently change the order. Once exhibits are re-published they go back to the original published order.

This is both an ov-wag and ov-frontend issue, so I'm not sure where to place it.

**Comment by mrharpo** [comment]
Sorting in Wagtail is not very customizable for pages. We can pick a default sort order, such as:
- `first_published_at` - This is the current behavior
- `last_published_at` - Sort by recently edited
- `title` - Alphabetical

We can choose to sort either ascending or descending on these options.

Unfortunately, we have to pick one for everyone. It would be difficult to modify it to something that a user can select. 

I vote for "most recently edited first".

**Comment by phigg** [comment]
I second your vote for "most recently edited first" / `last_published_at`. This will hopefully allow us to set the order by making changes.
