### ISSUE TITLE
Drafts URL contains draft signature/auth parameter

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/ov-wag#25]
Because:
Users need to be able to preview their drafts via the actual OV frontend before publication, but we don't want all drafts to be publicly available.

So, the backend needs to be able to provide an obscure redirect to the draft content without revealing other drafts.

Done When:

The wagtail backend can link an editor to view their draft page on the frontend, via an obfuscated URL.

**Comment by singlesoliloquy** [comment]
migrated https://helpdesk.wgbh.org/browse/MLAOV-10
