### ISSUE TITLE
Serializer-produced img elements in body field do not include full image url

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/ov-wag#61]
Because:
img elements embedded into an exhibit's body content come out like this:
![Screen Shot 2022-09-28 at 2.58.47 PM.png](https://images.zenhubusercontent.com/5d2cc7e91325bafe06bc11ae/f996bd73-cd7f-43f8-b2ca-b15a40d1d4ee)

rather than including the hostname in the image url as is returned by the ImageSerializer for dedicated image fields.

Done When:
img elements embedded in an Exhibit's body field are returned with the image's full URL via ImageSerializer.

**Comment by singlesoliloquy** [comment]
Migrated https://helpdesk.wgbh.org/browse/MLAOV-8

**Comment by jillpe** [comment]
Verify if this is done
